language: ruby
rvm:
 - 2.4.1
sudo: required --no-sandbox
addons:
  chrome: stable

before_script:
  - bundle install
  - bundle exec rails db:create db:test:prepare
script:
  - bundle exec rails ci:tests

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
services:
  - postgresql
